name: Install & Lint & Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.11.x
          cache: npm
      - name: Install
        run: npm ci
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: 'json'
      - name: Show files changed
        run: cat $HOME/files.json
      - name: Lint
        run: npm run lint
      - name: TSC
        run: npm run tsc
      - name: Test
        run: npm run test
      - name: SSH into Droplet
        uses: appleboy/ssh-action@master
        with:
          host: 167.71.254.50
          username: root
          key: ${{ secrets.DEPLOY_SECRET }}
          script: |
            cd workspaces/D2-Vendor-Alert/
            git pull
            pm2 restart 0
