name: Install & Lint & Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.11.x
          cache: npm
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_USER: ${{ secrets.DATABASE_USER }}
          envkey_DATABASE_CLUSTER: ${{ secrets.DATABASE_CLUSTER }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_DESTINY_API_KEY: ${{ secrets.DESTINY_API_KEY }}
          envkey_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          envkey_DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          envkey_DESTINY_OAUTH_CLIENT_ID: ${{ secrets.DESTINY_OAUTH_CLIENT_ID }}
          envkey_DESTINY_OAUTH_SECRET: ${{ secrets.DESTINY_OAUTH_SECRET }}
      - name: Install
        run: npm ci
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: 'json'
      - name: Show files changed
        run: cat $HOME/files.json
      - name: Lint
        run: npm run lint
      - name: TSC
        run: npm run tsc
      - name: Test
        run: npm run test
      - name: SSH into Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: root
          key: ${{ secrets.DEPLOY_SECRET }}
          script: |
            cd workspaces/D2-Vendor-Alert/
            git checkout .
            git pull
            npm install
            npm run tsc
            DATABASE_USER=${{ secrets.DATABASE_USER }} DATABASE_CLUSTER=${{ secrets.DATABASE_CLUSTER }} DATABASE_NAME=${{ secrets.DATABASE_NAME }} DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} DESTINY_API_KEY=${{ secrets.DESTINY_API_KEY }} DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} DESTINY_OAUTH_CLIENT_ID=${{ secrets.DESTINY_OAUTH_CLIENT_ID }} DESTINY_OAUTH_SECRET=${{ secrets.DESTINY_OAUTH_SECRET }} pm2 restart 0
